name: expense_tracker
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  bloc: ^8.1.4
  cupertino_icons: 1.0.8
  equatable: 2.0.5
  expense_repository:
    path: packages/expense_repository
  firebase_core: 2.32.0
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_colorpicker: ^1.1.0
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  intl: ^0.19.0
  uuid: ^4.4.2


dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
