// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ6yVHzkXRnqI_7F8_sctoLI7jR7EuNqQ',
    appId: '1:74661031713:web:a759c20b03aaf3c6631860',
    messagingSenderId: '74661031713',
    projectId: 'expense-tracker-9538e',
    authDomain: 'expense-tracker-9538e.firebaseapp.com',
    storageBucket: 'expense-tracker-9538e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfc2el2Yx2aUujyNodjYUwgI77v8asTwQ',
    appId: '1:74661031713:android:b895867147911573631860',
    messagingSenderId: '74661031713',
    projectId: 'expense-tracker-9538e',
    storageBucket: 'expense-tracker-9538e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuAu83oDUYbeJ6CkFbFxRns_IOEawbHEs',
    appId: '1:74661031713:ios:64f7ece396843598631860',
    messagingSenderId: '74661031713',
    projectId: 'expense-tracker-9538e',
    storageBucket: 'expense-tracker-9538e.appspot.com',
    iosBundleId: 'com.example.verygoodcore.expense-tracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuAu83oDUYbeJ6CkFbFxRns_IOEawbHEs',
    appId: '1:74661031713:ios:f15acd3bf200465f631860',
    messagingSenderId: '74661031713',
    projectId: 'expense-tracker-9538e',
    storageBucket: 'expense-tracker-9538e.appspot.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJ6yVHzkXRnqI_7F8_sctoLI7jR7EuNqQ',
    appId: '1:74661031713:web:ac052b2324c2077e631860',
    messagingSenderId: '74661031713',
    projectId: 'expense-tracker-9538e',
    authDomain: 'expense-tracker-9538e.firebaseapp.com',
    storageBucket: 'expense-tracker-9538e.appspot.com',
  );
}
